name: rmats4
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rmats=4.3.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-bsgenome.mmusculus.ucsc.mm10
  - bioconductor-bsgenome.mmusculus.ucsc.mm39